//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region Métadonnées de relation EDM

[assembly: EdmRelationshipAttribute("dbCashFlowModel.Model", "ProjetsUtilisateurs", "tableProject", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CashFlow.Models.tableProject), "tableUtilisateur", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(CashFlow.Models.tableUtilisateur))]

#endregion

namespace CashFlow.Models
{
    #region Contextes
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    public partial class dbCashFlowEntities1 : ObjectContext
    {
        #region Constructeurs
    
        /// <summary>
        /// Initialise un nouvel objet dbCashFlowEntities1 à l'aide de la chaîne de connexion trouvée dans la section 'dbCashFlowEntities1' du fichier de configuration d'application.
        /// </summary>
        public dbCashFlowEntities1() : base("name=dbCashFlowEntities1", "dbCashFlowEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialisez un nouvel objet dbCashFlowEntities1.
        /// </summary>
        public dbCashFlowEntities1(string connectionString) : base(connectionString, "dbCashFlowEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialisez un nouvel objet dbCashFlowEntities1.
        /// </summary>
        public dbCashFlowEntities1(EntityConnection connection) : base(connection, "dbCashFlowEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Méthodes partielles
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propriétés ObjectSet
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<sysdiagrams> sysdiagrams
        {
            get
            {
                if ((_sysdiagrams == null))
                {
                    _sysdiagrams = base.CreateObjectSet<sysdiagrams>("sysdiagrams");
                }
                return _sysdiagrams;
            }
        }
        private ObjectSet<sysdiagrams> _sysdiagrams;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<tableProject> tableProject
        {
            get
            {
                if ((_tableProject == null))
                {
                    _tableProject = base.CreateObjectSet<tableProject>("tableProject");
                }
                return _tableProject;
            }
        }
        private ObjectSet<tableProject> _tableProject;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<tableUtilisateur> tableUtilisateur
        {
            get
            {
                if ((_tableUtilisateur == null))
                {
                    _tableUtilisateur = base.CreateObjectSet<tableUtilisateur>("tableUtilisateur");
                }
                return _tableUtilisateur;
            }
        }
        private ObjectSet<tableUtilisateur> _tableUtilisateur;

        #endregion

        #region Méthodes AddTo
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet sysdiagrams. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddTosysdiagrams(sysdiagrams sysdiagrams)
        {
            base.AddObject("sysdiagrams", sysdiagrams);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet tableProject. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddTotableProject(tableProject tableProject)
        {
            base.AddObject("tableProject", tableProject);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet tableUtilisateur. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddTotableUtilisateur(tableUtilisateur tableUtilisateur)
        {
            base.AddObject("tableUtilisateur", tableUtilisateur);
        }

        #endregion

    }

    #endregion

    #region Entités
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbCashFlowModel.Model", Name="sysdiagrams")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sysdiagrams : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet sysdiagrams.
        /// </summary>
        /// <param name="name">Valeur initiale de la propriété name.</param>
        /// <param name="principal_id">Valeur initiale de la propriété principal_id.</param>
        /// <param name="diagram_id">Valeur initiale de la propriété diagram_id.</param>
        public static sysdiagrams Createsysdiagrams(global::System.String name, global::System.Int32 principal_id, global::System.Int32 diagram_id)
        {
            sysdiagrams sysdiagrams = new sysdiagrams();
            sysdiagrams.name = name;
            sysdiagrams.principal_id = principal_id;
            sysdiagrams.diagram_id = diagram_id;
            return sysdiagrams;
        }

        #endregion

        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 principal_id
        {
            get
            {
                return _principal_id;
            }
            set
            {
                Onprincipal_idChanging(value);
                ReportPropertyChanging("principal_id");
                _principal_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("principal_id");
                Onprincipal_idChanged();
            }
        }
        private global::System.Int32 _principal_id;
        partial void Onprincipal_idChanging(global::System.Int32 value);
        partial void Onprincipal_idChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 diagram_id
        {
            get
            {
                return _diagram_id;
            }
            set
            {
                if (_diagram_id != value)
                {
                    Ondiagram_idChanging(value);
                    ReportPropertyChanging("diagram_id");
                    _diagram_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("diagram_id");
                    Ondiagram_idChanged();
                }
            }
        }
        private global::System.Int32 _diagram_id;
        partial void Ondiagram_idChanging(global::System.Int32 value);
        partial void Ondiagram_idChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> version
        {
            get
            {
                return _version;
            }
            set
            {
                OnversionChanging(value);
                ReportPropertyChanging("version");
                _version = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("version");
                OnversionChanged();
            }
        }
        private Nullable<global::System.Int32> _version;
        partial void OnversionChanging(Nullable<global::System.Int32> value);
        partial void OnversionChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] definition
        {
            get
            {
                return StructuralObject.GetValidValue(_definition);
            }
            set
            {
                OndefinitionChanging(value);
                ReportPropertyChanging("definition");
                _definition = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("definition");
                OndefinitionChanged();
            }
        }
        private global::System.Byte[] _definition;
        partial void OndefinitionChanging(global::System.Byte[] value);
        partial void OndefinitionChanged();

        #endregion

    
    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbCashFlowModel.Model", Name="tableProject")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tableProject : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet tableProject.
        /// </summary>
        /// <param name="hash">Valeur initiale de la propriété Hash.</param>
        /// <param name="titre">Valeur initiale de la propriété Titre.</param>
        /// <param name="description">Valeur initiale de la propriété Description.</param>
        /// <param name="location">Valeur initiale de la propriété Location.</param>
        /// <param name="montantRecu">Valeur initiale de la propriété MontantRecu.</param>
        /// <param name="montantRequis">Valeur initiale de la propriété MontantRequis.</param>
        /// <param name="dateDebut">Valeur initiale de la propriété DateDebut.</param>
        /// <param name="dateLimite">Valeur initiale de la propriété DateLimite.</param>
        /// <param name="categorie">Valeur initiale de la propriété Categorie.</param>
        public static tableProject CreatetableProject(global::System.String hash, global::System.String titre, global::System.String description, global::System.String location, global::System.Decimal montantRecu, global::System.Decimal montantRequis, global::System.DateTime dateDebut, global::System.DateTime dateLimite, global::System.String categorie)
        {
            tableProject tableProject = new tableProject();
            tableProject.Hash = hash;
            tableProject.Titre = titre;
            tableProject.Description = description;
            tableProject.Location = location;
            tableProject.MontantRecu = montantRecu;
            tableProject.MontantRequis = montantRequis;
            tableProject.DateDebut = dateDebut;
            tableProject.DateLimite = dateLimite;
            tableProject.Categorie = categorie;
            return tableProject;
        }

        #endregion

        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Hash
        {
            get
            {
                return _Hash;
            }
            set
            {
                if (_Hash != value)
                {
                    OnHashChanging(value);
                    ReportPropertyChanging("Hash");
                    _Hash = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Hash");
                    OnHashChanged();
                }
            }
        }
        private global::System.String _Hash;
        partial void OnHashChanging(global::System.String value);
        partial void OnHashChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Titre
        {
            get
            {
                return _Titre;
            }
            set
            {
                OnTitreChanging(value);
                ReportPropertyChanging("Titre");
                _Titre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Titre");
                OnTitreChanged();
            }
        }
        private global::System.String _Titre;
        partial void OnTitreChanging(global::System.String value);
        partial void OnTitreChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Location
        {
            get
            {
                return _Location;
            }
            set
            {
                OnLocationChanging(value);
                ReportPropertyChanging("Location");
                _Location = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Location");
                OnLocationChanged();
            }
        }
        private global::System.String _Location;
        partial void OnLocationChanging(global::System.String value);
        partial void OnLocationChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal MontantRecu
        {
            get
            {
                return _MontantRecu;
            }
            set
            {
                OnMontantRecuChanging(value);
                ReportPropertyChanging("MontantRecu");
                _MontantRecu = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MontantRecu");
                OnMontantRecuChanged();
            }
        }
        private global::System.Decimal _MontantRecu;
        partial void OnMontantRecuChanging(global::System.Decimal value);
        partial void OnMontantRecuChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal MontantRequis
        {
            get
            {
                return _MontantRequis;
            }
            set
            {
                OnMontantRequisChanging(value);
                ReportPropertyChanging("MontantRequis");
                _MontantRequis = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MontantRequis");
                OnMontantRequisChanged();
            }
        }
        private global::System.Decimal _MontantRequis;
        partial void OnMontantRequisChanging(global::System.Decimal value);
        partial void OnMontantRequisChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateDebut
        {
            get
            {
                return _DateDebut;
            }
            set
            {
                OnDateDebutChanging(value);
                ReportPropertyChanging("DateDebut");
                _DateDebut = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateDebut");
                OnDateDebutChanged();
            }
        }
        private global::System.DateTime _DateDebut;
        partial void OnDateDebutChanging(global::System.DateTime value);
        partial void OnDateDebutChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateLimite
        {
            get
            {
                return _DateLimite;
            }
            set
            {
                OnDateLimiteChanging(value);
                ReportPropertyChanging("DateLimite");
                _DateLimite = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateLimite");
                OnDateLimiteChanged();
            }
        }
        private global::System.DateTime _DateLimite;
        partial void OnDateLimiteChanging(global::System.DateTime value);
        partial void OnDateLimiteChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Categorie
        {
            get
            {
                return _Categorie;
            }
            set
            {
                OnCategorieChanging(value);
                ReportPropertyChanging("Categorie");
                _Categorie = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Categorie");
                OnCategorieChanged();
            }
        }
        private global::System.String _Categorie;
        partial void OnCategorieChanging(global::System.String value);
        partial void OnCategorieChanged();

        #endregion

    
        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbCashFlowModel.Model", "ProjetsUtilisateurs", "tableUtilisateur")]
        public tableUtilisateur Createur
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tableUtilisateur>("dbCashFlowModel.Model.ProjetsUtilisateurs", "tableUtilisateur").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tableUtilisateur>("dbCashFlowModel.Model.ProjetsUtilisateurs", "tableUtilisateur").Value = value;
            }
        }
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tableUtilisateur> CreateurReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tableUtilisateur>("dbCashFlowModel.Model.ProjetsUtilisateurs", "tableUtilisateur");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tableUtilisateur>("dbCashFlowModel.Model.ProjetsUtilisateurs", "tableUtilisateur", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbCashFlowModel.Model", Name="tableUtilisateur")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tableUtilisateur : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet tableUtilisateur.
        /// </summary>
        /// <param name="username">Valeur initiale de la propriété Username.</param>
        /// <param name="email">Valeur initiale de la propriété Email.</param>
        /// <param name="password">Valeur initiale de la propriété Password.</param>
        /// <param name="nom">Valeur initiale de la propriété Nom.</param>
        public static tableUtilisateur CreatetableUtilisateur(global::System.String username, global::System.String email, global::System.String password, global::System.String nom)
        {
            tableUtilisateur tableUtilisateur = new tableUtilisateur();
            tableUtilisateur.Username = username;
            tableUtilisateur.Email = email;
            tableUtilisateur.Password = password;
            tableUtilisateur.Nom = nom;
            return tableUtilisateur;
        }

        #endregion

        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Username
        {
            get
            {
                return _Username;
            }
            set
            {
                if (_Username != value)
                {
                    OnUsernameChanging(value);
                    ReportPropertyChanging("Username");
                    _Username = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Username");
                    OnUsernameChanged();
                }
            }
        }
        private global::System.String _Username;
        partial void OnUsernameChanging(global::System.String value);
        partial void OnUsernameChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nom
        {
            get
            {
                return _Nom;
            }
            set
            {
                OnNomChanging(value);
                ReportPropertyChanging("Nom");
                _Nom = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nom");
                OnNomChanged();
            }
        }
        private global::System.String _Nom;
        partial void OnNomChanging(global::System.String value);
        partial void OnNomChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] PhotoProfile
        {
            get
            {
                return StructuralObject.GetValidValue(_PhotoProfile);
            }
            set
            {
                OnPhotoProfileChanging(value);
                ReportPropertyChanging("PhotoProfile");
                _PhotoProfile = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PhotoProfile");
                OnPhotoProfileChanged();
            }
        }
        private global::System.Byte[] _PhotoProfile;
        partial void OnPhotoProfileChanging(global::System.Byte[] value);
        partial void OnPhotoProfileChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Location
        {
            get
            {
                return _Location;
            }
            set
            {
                OnLocationChanging(value);
                ReportPropertyChanging("Location");
                _Location = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Location");
                OnLocationChanged();
            }
        }
        private global::System.String _Location;
        partial void OnLocationChanging(global::System.String value);
        partial void OnLocationChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Twitter
        {
            get
            {
                return _Twitter;
            }
            set
            {
                OnTwitterChanging(value);
                ReportPropertyChanging("Twitter");
                _Twitter = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Twitter");
                OnTwitterChanged();
            }
        }
        private global::System.String _Twitter;
        partial void OnTwitterChanging(global::System.String value);
        partial void OnTwitterChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Facebook
        {
            get
            {
                return _Facebook;
            }
            set
            {
                OnFacebookChanging(value);
                ReportPropertyChanging("Facebook");
                _Facebook = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Facebook");
                OnFacebookChanged();
            }
        }
        private global::System.String _Facebook;
        partial void OnFacebookChanging(global::System.String value);
        partial void OnFacebookChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GooglePlus
        {
            get
            {
                return _GooglePlus;
            }
            set
            {
                OnGooglePlusChanging(value);
                ReportPropertyChanging("GooglePlus");
                _GooglePlus = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("GooglePlus");
                OnGooglePlusChanged();
            }
        }
        private global::System.String _GooglePlus;
        partial void OnGooglePlusChanging(global::System.String value);
        partial void OnGooglePlusChanged();

        #endregion

    
        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbCashFlowModel.Model", "ProjetsUtilisateurs", "tableProject")]
        public EntityCollection<tableProject> Projet
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tableProject>("dbCashFlowModel.Model.ProjetsUtilisateurs", "tableProject");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tableProject>("dbCashFlowModel.Model.ProjetsUtilisateurs", "tableProject", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
